<div class="">
    <form action="?route=register/store" method="post">
        <div class="form-group">
            <label for="name">name</label>
            <input type="text" name="name" class="form-control">
        </div>

        <div class="form-group">
            <label for="email">email</label>
            <input type="text" name="email" class="form-control">
        </div>

        <div class="form-group">
            <label for="pass">password</label>
            <input type="text" name="pass" class="form-control">
        </div>

        <button class="btn btn-primary" type="submit">Save</button>
    </form>
</div>